package Equacao;

public class Segundo_grau extends javax.swing.JFrame {

        public Segundo_grau() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_valorA = new javax.swing.JLabel();
        lbl_valorB = new javax.swing.JLabel();
        lbl_valorC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_valorA = new javax.swing.JTextField();
        txt_valorB = new javax.swing.JTextField();
        txt_valorC = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        lbl_resposta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_valorA.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_valorA.setText("Valor do A");

        lbl_valorB.setText("Valor do B");

        lbl_valorC.setText("Valor do C");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("Equação do 2° Grau");

        txt_valorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_valorAActionPerformed(evt);
            }
        });

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        lbl_resposta.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_calcular)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_valorA)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_valorA))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_valorB)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_valorB))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_valorC)
                                            .addGap(18, 18, 18)
                                            .addComponent(txt_valorC, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))))))
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addComponent(lbl_resposta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valorA)
                    .addComponent(txt_valorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valorB)
                    .addComponent(txt_valorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valorC)
                    .addComponent(txt_valorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btn_calcular)
                .addGap(18, 18, 18)
                .addComponent(lbl_resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        private void txt_valorAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_valorAActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_valorAActionPerformed

        private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_calcularActionPerformed

                String valorA = txt_valorA.getText();
                String valorB = txt_valorB.getText();
                String valorC = txt_valorC.getText();

                double a = Double.parseDouble(valorA);
                double b = Double.parseDouble(valorB);
                double c = Double.parseDouble(valorC);

                if (a == 0) {
                        lbl_resposta.setText("Valor do A não pode ser 0");
                } else {
                        double resultadoDelta = Math.pow(b, 2) - 4 * a * c;

                        double resultadoX = ((b * -1) + (Math.sqrt(resultadoDelta))) / (2 * a);

                        double resultadoX2 = ((b * -1) - (Math.sqrt(resultadoDelta))) / (2 * a);

                        lbl_resposta.setText(Double.toString(resultadoDelta) + " x1:" + Double.toString(resultadoX)
                                        + " x2:" + Double.toString(resultadoX2));
                }

        }// GEN-LAST:event_btn_calcularActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Segundo_grau.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Segundo_grau.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Segundo_grau.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Segundo_grau.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Segundo_grau().setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_resposta;
    private javax.swing.JLabel lbl_valorA;
    private javax.swing.JLabel lbl_valorB;
    private javax.swing.JLabel lbl_valorC;
    private javax.swing.JTextField txt_valorA;
    private javax.swing.JTextField txt_valorB;
    private javax.swing.JTextField txt_valorC;
    // End of variables declaration//GEN-END:variables
}
